name: STM32MP157 Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up environment
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential git wget bzip2 \
        python3 python3-pip python3-setuptools python3-wheel \
        device-tree-compiler bc u-boot-tools gcc-arm-none-eabi gcc-arm-linux-gnueabihf

    - name: Build U-Boot
      run: |
        git clone https://github.com/u-boot/u-boot.git
        cd u-boot
        export CROSS_COMPILE=arm-none-eabi-
        export ARCH=arm
        make stm32mp15_defconfig
        make -j$(nproc)

    - name: Build Linux Kernel
      run: |
        git clone https://github.com/STMicroelectronics/linux.git
        cd linux
        export CROSS_COMPILE=arm-linux-gnueabihf-
        export ARCH=arm
        make stm32mp157c-dk2_defconfig
        make -j$(nproc) uImage dtbs

    - name: Build RootFS
      run: |
        wget https://buildroot.org/downloads/buildroot-2023.02.tar.bz2
        tar -xjf buildroot-2023.02.tar.bz2
        cd buildroot-2023.02
        make stm32mp157_dk_defconfig
        make -j$(nproc)

    - name: Package Image
      run: |
        mkdir -p output
        cp u-boot/u-boot.bin output/
        cp linux/arch/arm/boot/uImage output/
        cp linux/arch/arm/boot/dts/stm32mp157c-dk2.dtb output/
        cp buildroot-2023.02/output/images/rootfs.cpio.gz output/
        tar -czvf stm32mp157_image.tar.gz -C output .

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: stm32mp157_image
        path: stm32mp157_image.tar.gz
