name: STM32MP157 Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  ARCH: arm
  CROSS_COMPILE: arm-none-eabi-

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up environment
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential git wget bzip2 \
        python3 python3-pip python3-setuptools python3-wheel \
        device-tree-compiler bc u-boot-tools libgnutls28-dev \
        gcc-arm-none-eabi debootstrap parted

    - name: Check ARM compiler version
      run: |
        arm-none-eabi-gcc --version

    - name: Cache U-Boot
      uses: actions/cache@v4
      with:
        path: u-boot
        key: u-boot-${{ runner.os }}-${{ hashFiles('u-boot/**') }}
        restore-keys: |
          u-boot-${{ runner.os }}-

    - name: Build U-Boot
      run: |
        if [ -d "u-boot" ]; then
          rm -rf u-boot
        fi
        git clone https://github.com/u-boot/u-boot.git
        cd u-boot
        make stm32mp15_defconfig
        make -j$(nproc)

    - name: Cache Linux Kernel
      uses: actions/cache@v4
      with:
        path: linux
        key: linux-${{ runner.os }}-${{ hashFiles('linux/**') }}
        restore-keys: |
          linux-${{ runner.os }}-

    - name: Clone Linux Kernel
      run: |
        if [ -d "linux" ]; then
          rm -rf linux
        fi
        git clone https://github.com/STMicroelectronics/linux.git
        cd linux
        git checkout v6.1-stm32mp

    - name: List available defconfigs
      run: |
        cd linux
        ls arch/arm/configs/

    - name: Generate kernel configuration
      run: |
        cd linux
        make stm32_defconfig

    - name: Modify kernel configuration
      run: |
        cd linux
        sed -i 's/CONFIG_XIP_KERNEL=y/# CONFIG_XIP_KERNEL is not set/' .config

    - name: Build Linux Kernel
      run: |
        cd linux
        make -j$(nproc) uImage dtbs

    - name: Build Ubuntu RootFS
      run: |
        sudo mkdir /mnt/ubuntu-rootfs
        sudo debootstrap focal /mnt/ubuntu-rootfs http://archive.ubuntu.com/ubuntu/

        sudo mount --bind /dev /mnt/ubuntu-rootfs/dev
        sudo mount --bind /proc /mnt/ubuntu-rootfs/proc
        sudo mount --bind /sys /mnt/ubuntu-rootfs/sys

        sudo cp /etc/passwd /mnt/ubuntu-rootfs/etc/
        sudo cp /etc/shadow /mnt/ubuntu-rootfs/etc/
        sudo cp /etc/group /mnt/ubuntu-rootfs/etc/

        sudo chroot /mnt/ubuntu-rootfs bash -c "echo 'root:password' | chpasswd"
        sudo chroot /mnt/ubuntu-rootfs bash -c "echo 'ubuntu:password' | chpasswd || true"

        sudo chroot /mnt/ubuntu-rootfs apt-get update
        sudo chroot /mnt/ubuntu-rootfs apt-get install -y systemd-sysv dbus network-manager sudo ssh

        sudo chroot /mnt/ubuntu-rootfs bash -c "echo 'auto lo' > /etc/network/interfaces"
        sudo chroot /mnt/ubuntu-rootfs bash -c "echo 'iface lo inet loopback' >> /etc/network/interfaces"

        sudo chroot /mnt/ubuntu-rootfs useradd -m -s /bin/bash ubuntu
        sudo chroot /mnt/ubuntu-rootfs usermod -aG sudo ubuntu

        sudo umount /mnt/ubuntu-rootfs/dev
        sudo umount /mnt/ubuntu-rootfs/proc
        sudo umount /mnt/ubuntu-rootfs/sys

        sudo tar -czvf ubuntu-rootfs.tar.gz -C /mnt/ubuntu-rootfs .

    - name: Create SD Card Image
      run: |
        # Создаем пустой образ размером 2 ГБ
        dd if=/dev/zero of=stm32mp157_image.img bs=1M count=2048

        # Создаем таблицу разделов (msdos)
        sudo parted stm32mp157_image.img mklabel msdos

        # Создаем раздел boot (FAT32)
        sudo parted stm32mp157_image.img mkpart primary fat32 1MiB 257MiB

        # Создаем раздел rootfs (ext4)
        sudo parted stm32mp157_image.img mkpart primary ext4 257MiB 100%

        # Форматируем раздел boot (FAT32)
        sudo mkfs.vfat -n "BOOT" --offset $((1 * 2048)) stm32mp157_image.img $((255 * 2048))

        # Форматируем раздел rootfs (ext4)
        sudo mkfs.ext4 -L "ROOTFS" -E offset=$((256 * 2048 * 512)) stm32mp157_image.img $((1792 * 2048))

        # Создаем временные директории для монтирования
        mkdir -p ./mnt/boot
        mkdir -p ./mnt/rootfs

        # Монтируем раздел boot
        sudo mount -o loop,offset=$((1 * 2048 * 512)) stm32mp157_image.img ./mnt/boot

        # Копируем файлы U-Boot, ядра и DTB
        sudo cp u-boot/u-boot.bin ./mnt/boot/
        sudo cp linux/arch/arm/boot/uImage ./mnt/boot/
        sudo cp linux/arch/arm/boot/dts/stm32mp157c-dk2.dtb ./mnt/boot/

        # Размонтируем раздел boot
        sudo umount ./mnt/boot

        # Монтируем раздел rootfs
        sudo mount -o loop,offset=$((256 * 2048 * 512)) stm32mp157_image.img ./mnt/rootfs

        # Копируем корневую файловую систему
        sudo tar -xzvf ubuntu-rootfs.tar.gz -C ./mnt/rootfs

        # Размонтируем раздел rootfs
        sudo umount ./mnt/rootfs

    - name: Clean up
      run: |
        rm -rf ./mnt/boot
        rm -rf ./mnt/rootfs
        rm stm32mp157_image.img
        rm ubuntu-rootfs.tar.gz

    - name: Upload SD Card Image
      uses: actions/upload-artifact@v4
      with:
        name: stm32mp157_image
        path: stm32mp157_image.img
    - name: Notify Completion
      run: |
        echo "Создание образа SD-карты завершено успешно."
        echo "Образ доступен для загрузки."
